name: Build

on:
  push:
    paths:
      - ".github/workflows/build.yml"
      - "app/**"
  pull_request:
    paths:
      - ".github/workflows/build.yml"
      - "app/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker.io/zmkfirmware/zmk-build-arm:3.5
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache west modules
        uses: actions/cache@v4
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('app/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
        timeout-minutes: 2
        continue-on-error: true

      - name: Initialize workspace (west init)
        run: west init -l app

      - name: Update modules (west update)
        run: west update

      - name: Export Zephyr CMake package (west zephyr-export)
        run: west zephyr-export

      - name: Build choctopus44
        run: west build -s app -p -b nice_nano_v2 -- -DSHIELD="choctopus44" -DSNIPPET="zmk-usb-logging"

      - name: Rename artifact
        run: |
          mkdir -p artifacts
          cp build/zephyr/zmk.uf2 artifacts/nice_nano_v2-choctopus44-zmk.uf2 || true

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: artifacts/
